= Prozessorientierter Ansatz

[,ISO 9001 (2015), Kapitel 0.1]
____
Diese Internationale Norm wendet den prozessorientierten Ansatz an, der das Planen-Durchführen-Prüfen-Handeln-Modell (englisch: Plan-Do-Check-Act) sowie risikobasiertes Denken umfasst.
____

Das bedeutet, dass ein qualitätsorientiertes Unternehmen seine Prozesse genau kennen muss.
In Gedanken zähle ich die Prozesse auf, die mir sofort einfallen, weil ich selbst beteiligt bin.
Der von uns gelebte agile Entwicklungsprozess mit Scrum.
Eh klar.
Der Prozess zur Lenkung von Anforderungen bei einem unserer Kunden, für den ich als Berater tätig bin. Auch klar.
Die Erfassung meiner Arbeitszeit und der Abrechnungsprozess.
Die Weiterbildung.

Je mehr ich über meine eigenen Tätigkeiten nachdenke, desto mehr frage ich mich, welche anderen Prozesse es noch gibt.

« Welche Prozesse lebt mein Chef? »

« Wer organisiert die Büroreinigung? »

« Was passiert, wenn die Alarmanlage eine Störung hat? »

Prozesse sind immer wieder auf bewährte Art und Weise ausgeführte Abfolgen von Tätigkeiten.
Schnell wird mir klar, dass es mehr Tätigkeiten in einem Unternehmen gibt, als man im ersten Moment annimmt.
Gerade jene häufig als "trivial" bezeichneten Tätigkeiten, die einem nicht sofort einfallen, die nur einmal im Jahr oder nur bei Störungen durchgeführt werden, sind nicht selten Wissensinseln bei einzelnen Personen im Unternehmen.
Denkt man darüber nach, wird schnell klar:
Prozesse sind wichtig.
Sie haben einen Wert.
Kontinuierliche Verbesserung der Prozesse ist eine Chance,direkt oder indirekt die Qualität der Produkte des Unternehmens zu verbessern.
Der Verlust von Wissen über die Prozesse ist hingegen ein Risiko.

In der Systematik von cards+ ist ein Prozess ein Baustein in der Systembeschreibung des Managementsystems mit folgenden Eigenschaften:

* Titel
* Zweck
* Besitzer
* Qualitätsziele
* Risiken und Chancen
* Tätigkeiten

Mit diesem Katalog an Eigenschaften ergibt sich ein doch recht komplexer Baustein mit Abhängigkeiten zu weiteren Bausteinen.
Bei der weiteren Detaillierung der Prozesse ergeben sie die Bausteinen für Richtlinien, Leitfäden und Arbeitsaufträge.
