= Der digitale Wandel ist eine Chance für KMU

KMU bilden das Rückgrat unserer Wirtschaft, sagt die österreichische Bundesministerin Dr. Margarete Schramböck.
Dr. Harald Mahrer, Präsident der Wirtschaftskammer in Österreich, sagt, dass KMU rund sieben von zehn Arbeitsplätzen in Österreich sichern.
KMU sind vom digitalen Wandel direkt betroffen.
Digitale Technologien sind zum Schlüssel für wirtschaftlichen Erfolg geworden, nicht nur für große Unternehmen.
Auch ein KMU sollte über Digitalisierung nachdenken.

Aber was bedeutet digitaler Wandel für ein KMU?

In meinem letzten Beitrag habe ich eine Geschichte von einem Unternehmer erzählt, der seit vielen Jahren eine individuelle Anwendung verwendet.
Die Anwendung für die Leistungserfassung hat einen hohen Wert für den Unternehmer.
Sie unterstützt *optimal* seine ganz spezielle Arbeitsweise bei der Planung, Durchführung und Abrechnung seiner Leistungen.
Der Unternehmer ist erfolgreich.
Die Anwendung ist Teil des Erfolges.
Die Entwicklungs des Marktes, neue Kundenbeziehungen oder gesetzliche Regelungen verändern auch dieses Unternehmen.
Die Anwendung muss *laufend* an diese kontinuierlichen Veränderungen angepasst werden.
Der digitale Weg ist ein Weg der kontinuierlichen Veränderung.

Andere Unternehmen setzen auf Standardsoftware.
Sie bieten vielfältige Funktionen:
Leistungserfassung, Warenwirtschaft, Buchhaltung, Rechnungswesen.
Das Angebot ist groß.

- SevDesk (https://sevdesk.at) bezeichnet sich selbst als Software für Buchhaltung.

- Helium5 (https://www.helium5.com) erfüllt alle Anforderungen an eine Software für Einkauf, Verkauf, Warenwirtschaft, Produktion, Zeiterfassung, Finanzbuchhaltung, Reklamationsverwaltung und für die Instandhaltung.

Die beiden Beispiele markieren in etwa die Eckpunkt im Spektrum der Standardsoftware.

Die Funktionen der *ersten* Anwendung decken einen wichtigen Bereich in der Abwicklung von Leistungen in einem Unternehmen ab.
Für andere Bereiche ist allerdings eine andere Anwendung notwendig.
Das führt in vielen Unternehmen zu einem Flickenteppich von Software unterschiedlicher Hersteller.
Jede Anwendung sieht anders aus, verhält sich anders.
Ein direktes Zusammenspiel der Anwendungen ist in der Regel nicht möglich.
Stammdaten müssen mehrfach eingegeben werden.
Das birgt ein großes Risiko für Inkonsistenzen in den Daten.
Beschäftigte benötigen Konten in allen Anwendungen.
Eine Herausforderung für die Administration.

In der *zweiten* Anwendung sind praktisch alle Funktionen integriert, die ein kleines Unternehmen braucht.
Der Funktionsumfang ist riesig.
Die Anwendung kann viel mehr, als der Unternehmer tatsächlich braucht.
In festen Genzen ist eine Anpassung möglich.
Das reicht vielen Unternehmern.
In manchen Abläufen müssen sie aber ihre Arbeitsweise oder die ihrer Beschäftigten an die Vorgaben anpassen, die durch die Standardsoftware bestimmt werden.

Erfolgreiche Unternehmer gehen ihren eigenen Weg.
Der Einsatz von Standardsoftware bedeutet für sie Kompromisse.
Die Hersteller von Standardsoftware bieten eine funktionierend Lösung.
Sie kann aber niemals den Unterschied machen.

Ich vermute, die Lösungen in den Unternehmen sind so vielfältig wie die Angebote, die es am Markt für Standardsoftware gibt.
Spezielle Abkäufe im Unternehmen werden organisatorisch geregelt, ohne Unterstützung durch Software.
Enagierte Beschäftigte schließen solche Lücken häufig mit individuellen Insellösungen.
Dienstpläne sind ein typisches Beispiel.
Führungskräfte planen den Dienst mit
https://www.ionos.at/startupguide/produktivitaet/dienstplan-erstellen-in-excel[Excel-Dateien].
Die Planung stellt sicher, dass die richtige Anzahl an Beschäftigten mit der richtigen Qualifikation zur richtigen Zeit am richtigen Ort im Einsatz sind.
Der Dienstplan legt den Beginn und das Ende von Arbeitszeiten fest.
Die Planung wird laufend an die aktuelle Situation angepasst, z.B. bei ungeplanten Ausfällen beim Personal.
Die Beschäftigten melden die tatsächlichen Arbeitszeiten oder tragen sie selbst im Dienstplan ein.
Einmal im Monat wird der Dienstplan verifiziert und die Ergebnisse in die Standardsoftware eingetragen.

tbd Fazit
