= Warum nicht kontinuierlich Dokumentieren?

In dem Beitrag mit dem Titel "Shifting to Continuous Documentation as a New Approach for Code Knowledge" erklärt der Autor das Prinzip der kontinuierlichen Dokumentation.
Er bezieht sich dabei auf andere Prinzipien, die in der modernen Software-Entwicklung nicht mehr wegzudenken sind.
Wir bauen und testen unsere Software kontinuierlich mit dem Ziel, früh Fehler zu entdecken (fail fast) und nennen es _Continuous Integration_.
Wir liefern unsere Software häufig mit dem Ziel, sie in kleinen gut testbaren Schritten zu verändern und nennen es _Continuous Deployment_.
Wir liefern die Software in kurzen Abständen mit dem Ziel, auf jeden Bedarf der Kunden und Nutzer sicher und schnell zu reagieren und nennen es _Continuous Delivery_.
Warum dokumentieren wir unserer Software nicht auch kontinuierlich und nennen es _Continuous Documentation_?

> Continuous Documentation is the process that optimizes and reduces drift between the codebase and code-specific knowledge. Continuous Documentation applies the paradigm of automated integration of documentation into the development pipelines, by building and updating documentation incrementally, thereby keeping it in sync with the codebase. Continuous Documentation means that the Documentation is Always up-to-date; Created when best and code-coupled.

https://www.infoq.com/articles/continuous-documentation/

---

Dokumentation ist keine Option bei der Entwicklung einer nicht trivialen Software.
Sie ist notwendig, um die gewünschte Geschwindigkeit bei der Realisierung neuer Funktionen zu erreichen, ohne die Qualität der Software insgesamt zu gefährden.

Dokumentation ist wichtiges Wissen.
Selbst ein sehr gut lesbarer Code kann nur erklären, wie etwas funktioniert.
Wer wann was mit der Software tut kann Code alleine kaum erklären.

Dokumentation sollte korrekt sein.
Sie muss geprüft werden.
Dafür muss sie prüfbar sein.
Es muss Kritierien geben, um entscheiden zu können, ob etwas richtig oder falsch ist.

Dokumentation sollte vollständig sein.
Dafür muss bekannt sein, was 100% bedeutet.
Es muss ein definiertes Soll geben.

---

Dokumentieren ist ein kreativer Prozess.
Er kann nicht komplett automatisiert werden.
Ein Architekturbild muss auf den Punkt bringen, um was es geht.
Es ist eine Visualisierung für das große Ganze, reduziert auf die Kernkomponenten.
Eine Vision muss der Kunde verstehen.
Sie muss in seiner Sprache geschrieben sein.
Sie ist wichtiger Input für die Entwicklung.

Spezifizieren ist das Präzisieren von geforderten Fähigkeiten einer Software.
In einem agilen Entwicklungsprozess wird inkrementell spezifiziert.
Jeder Fortschritt in der Implementierung führt zu einer Veränderung in der Spezifikation.
Eine Spezifikation ist eine code-gekoppelte Dokumentation.
Aufgrund der Nähe zum Code muss eine Spezifikation mit dem Code zusammen versioniert werden.

Für eine Spezifikation bietet sich `Asciidoc` als Format an.
Eine Konfigurationsdatei oder jede Schemadatei für Json, Avro, Protobuf oder XML kann mit der `source`-Direktive direkt als Spezifikation verwendet werden.
Sauberer Code, ausgeschnitten mit der `include`-Direktive von Asciidoc, oder Asciidoc-Fragmente, generiert mit Spring REST Docs, werden mit einer Überschrift und einen einführenden Satz versehen zur perfekten Beschreibung.
Mit Asciidoc können einfach Tabellen gestaltet werden.
Die Daten können aus einer CSV-Datei geladen werden.
Mit der Diagramm-Erweiterung von Asciidoc werden einf

Zum Abschluss noch eine Bemerkung.


Also ein drittes CD?


Warum aktualisieren wir die Spezifikation unserer Software nicht auch kontinuierlich und nennen es _Continuous Specification_?


Wir müssen die Art und Weise, wie wir Dokumentation erstellen und konsumieren, ändern und den Prinzipien der kontinuierlichen Dokumentation folgen: die Erstellung von code-gekoppelter Dokumentation



