= Der digitale Wandel ist eine Chance für KMU

KMU bilden das Rückgrat unserer Wirtschaft, sagt die österreichische Bundesministerin Dr. Margarete Schramböck.
Dr. Harald Mahrer, Präsident der Wirtschaftskammer in Österreich, sagt, dass KMU rund sieben von zehn Arbeitsplätzen in Österreich sichern.
KMU sind vom digitalen Wandel direkt betroffen.
Digitale Technologien sind zum Schlüssel für wirtschaftlichen Erfolg geworden, nicht nur für große Unternehmen.
Auch ein KMU sollte über Digitalisierung nachdenken.

Aber was bedeutet digitaler Wandel für ein KMU?

In meinem letzten Beitrag habe ich eine Geschichte von einem Unternehmer erzählt, der seit vielen Jahren eine individuelle Anwendung verwendet.
Die Anwendung für die Leistungserfassung hat einen hohen Wert für den Unternehmer.
Sie unterstützt *optimal* seine ganz spezielle Arbeitsweise bei der Planung, Durchführung und Abrechnung seiner Leistungen.
Der Unternehmer ist erfolgreich.
Die Anwendung ist Teil des Erfolges.
Die Entwicklungs des Marktes, neue Kundenbeziehungen oder gesetzliche Regelungen verändern auch dieses Unternehmen.
Die Anwendung muss *laufend* an diese kontinuierlichen Veränderungen angepasst werden.
Der digitale Weg ist ein Weg der kontinuierlichen Veränderung.

Andere Unternehmen setzen auf Standardsoftware.
Sie bieten vielfältige Funktionen:
Leistungserfassung, Warenwirtschaft, Buchhaltung, Rechnungswesen.
Das Angebot ist groß.

- SevDesk (https://sevdesk.at) wird vom Hersteller als Software für Buchhaltung bezeichnet.

- Helium5 (https://helium5.com) erfüllt nach Angaben des Hetstellers alle Anforderungen an eine Software für Einkauf, Verkauf, Warenwirtschaft, Produktion, Zeiterfassung, Finanzbuchhaltung, Reklamationsverwaltung und für die Instandhaltung.

Die beiden Beispiele markieren in etwa die Eckpunkte im Spektrum der Standardsoftware.

Die Funktionen der *ersten* Anwendung decken einen wichtigen Bereich in der Abwicklung von Leistungen in einem Unternehmen ab.
Für andere Bereiche ist allerdings eine andere Anwendung notwendig.
Das führt in vielen Unternehmen zu einem Flickenteppich von Software unterschiedlicher Hersteller.
Jede Anwendung sieht anders aus, verhält sich anders.
Ein direktes Zusammenspiel der Anwendungen ist in der Regel nicht möglich.
Stammdaten müssen mehrfach eingegeben werden.
Das birgt ein großes Risiko für Inkonsistenzen in den Daten.
Beschäftigte benötigen Konten in allen Anwendungen.
Eine Herausforderung für die Administration.

In der *zweiten* Anwendung sind praktisch alle Funktionen integriert, die ein kleines Unternehmen braucht.
Der Funktionsumfang ist riesig.
Die Anwendung kann viel mehr, als der Unternehmer tatsächlich braucht.
In festen Genzen ist eine Anpassung möglich.
Das reicht vielen Unternehmern.
In manchen Abläufen müssen sie aber ihre Arbeitsweise oder die ihrer Beschäftigten an die Vorgaben anpassen, die durch die Standardsoftware bestimmt werden.

Erfolgreiche Unternehmer gehen ihren eigenen Weg.
Der Einsatz von Standardsoftware bedeutet für sie Kompromisse.
Spezielle Abkäufe im Unternehmen werden organisatorisch geregelt, ohne Unterstützung durch Software.
Enagierte Beschäftigte schließen solche Lücken häufig mit individuellen Insellösungen.
Dienstpläne sind ein typisches Beispiel.
Führungskräfte planen den Dienst mit
https://www.ionos.at/startupguide/produktivitaet/dienstplan-erstellen-in-excel[Excel-Dateien].
Die Planung stellt sicher, dass die richtige Anzahl an Beschäftigten mit der richtigen Qualifikation zur richtigen Zeit am richtigen Ort im Einsatz sind.
Der Dienstplan legt den Beginn und das Ende von Arbeitszeiten fest.
Die Planung wird laufend an die aktuelle Situation angepasst, z.B. bei ungeplanten Ausfällen beim Personal.
Die Beschäftigten melden die tatsächlichen Arbeitszeiten oder tragen sie selbst im Dienstplan ein.
Einmal im Monat wird der Dienstplan verifiziert und die Ergebnisse in die Standardsoftware für Zeiterfassung eingetragen.

Ich vermute, die Lösungen in den kleinen Unternehmen sind so vielfältig wie die Angebote, die es am Markt für Standardsoftware gibt.
Standardsoftware wird mit individuellen Insellösungen kombiniert.
Sie sind Ausdruck der Individualität des Unternehmens.
Ein Erfolgsfaktor. 

Standardsoftware zeichnet sich durch Qualität und Zuverlässigkeit aus.
Sie ist angemessen dokumentiert.
Es gibt Unterstützung bei der Installation oder bei Problemen.
Sie wird gewartet, d.h. Fehler werden korrigiert und Lücken geschlossen.

Eine individuelle Insellösung passt optimal zu den Arbeitsabläufen im Unternehmen.
Sie wird sehr häufig von einer Person erfunden, die dadurch effizienter ihre Aufgaben erledigen kann.
Die Lösung ist kaum dokumentiert.
Nur ganz wenige Personen sind in der Lage, Fehler zu korrigieren oder Lücken zu schließen.
Verlässt diese Person das Unternehmen, ist das sehr häufig das Ende für die Lösung.

Das ist ein kleines Dilemma.
Standardsoftware kann eine individuelle Insellösungen nicht oder nur mit kostenpflichtiger Anpassung (Stichwort Customizing) ersetzen.
Der Austausch einer Standardsoftware durch eine andere, leistungsfähigere Standardsoftware bedeutet eine risikoreiche und teure Migration.
Der Einsatz einer nicht dokumentierten individuellen Lösung stellt für ein kleines Unternehmen ebenfalls ein nicht zu unterschätzendes Risiko dar.

Der digitale Wandel ist eine Chance für ein KMU, individuelle Insellösungen in der gleichen Qualität und mit der selben Zuverlässigkeit wie Standardsoftware zu realisieren.
Ziel ist nicht, Standardsoftware durch individuelle Anwendungen zu ersetzen.
Leistbare, agil entwickelte und individuell gestaltete Anwendungen sollen Standardsoftware ergänzen.
Und zwar als Ausdruck der Individualität des Unternehmens.

---

Gerne beantworte ich dazu auch Fragen in dieser Gruppe.
Die Ungeduldigen können sich den Quelltext der Anwendung mit etwas reduzierter Funktionalität sofort im Github-Repository

https://github.com/cardsplus/bootscs

anschauen. Das Projekt dient als Beispiel für meine kommenden Beiträge.
