= Der digitale Wandel ist eine Chance für KMU

KMU bilden das Rückgrat unserer Wirtschaft, sagt die österreichische Bundesministerin Dr. Margarete Schramböck.
Dr. Harald Mahrer, Präsident der Wirtschaftskammer in Österreich, sagt, dass KMU rund sieben von zehn Arbeitsplätzen in Österreich sichern.
KMU sind vom digitalen Wandel direkt betroffen.
Digitale Technologien sind zum Schlüssel für wirtschaftlichen Erfolg geworden, nicht nur für große Unternehmen.
Auch ein KMU sollte über Digitalisierung nachdenken.

Aber was bedeutet digitaler Wandel für ein KMU?

In meinem letzten Beitrag habe ich eine Geschichte von einem Unternehmer erzählt, der seit vielen Jahren eine individuelle Anwendung verwendet.
Die Anwendung für die Leistungserfassung hat einen hohen Wert für den Unternehmer.
Sie unterstützt *optimal* seine ganz spezielle Arbeitsweise bei der Planung, Durchführung und Abrechnung seiner Leistungen.
Der Unternehmer ist mit diesem Weg erfolgreich.
Die Entwicklungs des Marktes, neue Kundenbeziehungen oder gesetzliche Regelungen verändern auch dieses Unternehmen.
Die Anwendung muss aber mit an diese kontinuierlichen Veränderungen angepasst werden.
Der digitale Weg ist ein Weg der kontinuierlichen Veränderung.
